# docker build --no-cache -t topic-yarp-api:latest -f dockerfile-topic-yarp-api .
# docker run -d -p 6330:8080 --name topic-yarp-api topic-yarp-api:latest

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["src/ApiGateways/YarpApi/YarpApi.csproj", "src/ApiGateways/YarpApi/"]

# Восстанавливаем зависимости
RUN dotnet restore "src/ApiGateways/YarpApi/YarpApi.csproj"

COPY . .

RUN dotnet build "src/ApiGateways/YarpApi/YarpApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "src/ApiGateways/YarpApi/YarpApi.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "YarpApi.dll"]